app-name: roster
initials: nrm
language: gradle

github-app-repo-uri: "git@github.com:NR-Martin/roster.git"

github-pipelines-repo-uri: "git@github.com:NR-Martin/training-pipelines.git"

cf-dev-api: api.run.pivotal.io
cf-dev-org: rscale-training-2
cf-dev-space: nick
cf-dev-hostname: roster-nmartin
cf-dev-domain: cfapps.io
cf-dev-manifest: manifest.yml
